my_string=input('Введите любое слово: ')
print(my_string)
print('Длина строчки: ' + str(len(my_string)))
print('Верхний регистр: ' + my_string.upper())
print('Удаляем все пробелы: ' + str(my_string.replace(__old:= ' ',__new:= '')))
print('Нижний регистр: ' + my_string.lower())
print('Первая буква строки: ' + my_string[0])
print('Последняя буква строки: ' + my_string[-1])
